- name: docker gpg setup
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    update_cache: yes
    state: present

- name: Update repositories cache
  apt:
    update_cache: yes


- name: Install docker-ce
  apt:
    name: docker-ce

- name: add ubuntu to docker
  user:
    name: ubuntu
    group: docker

- name: add ansibleuser to docker
  user:
    name: ansibleuser
    group: docker

- name: install pip for ansible docker
  apt:
    pkg:
      - python3-pip

- name: install docker python for anisble
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  with_items:
    - { name: docker, version: 2.0.0 }
    # - { name: docker-py, version: 1.10.6 }