- name: grafana gpg setup
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: add grafana apt repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    update_cache: yes
    state: present

- name: Update repositories cache
  apt:
    update_cache: yes

- name: Install grafana
  apt:
    name: grafana

- name: enable verbose mode
  ini_file: dest=/etc/grafana/grafana.ini section=server option=domain value=example.com backup=yes

- name: enable verbose mode
  ini_file: dest=/etc/grafana/grafana.ini section=server option=root_url value=%(protocol)s://%(domain)s:%(http_port)s/grafana/ backup=yes

- name: enable verbose mode
  ini_file: dest=/etc/grafana/grafana.ini section=server option=serve_from_sub_path value=true backup=yes
  # tags: configuration

- name: Restart grafana
  systemd:
    state: restarted
    name: grafana-server
    daemon_reload: yes
