- become: yes
  hosts: bastion
  name: deploy-linkin
  roles:
    # - docker
    # - docker-compose
    - common
    - nginx

- become: yes
  hosts: development
  name: deploy-linkin
  roles:
    # - docker
    # - docker-compose
    - common
    - postgres
