- become: yes
  hosts: development
  name: setup-pg
  roles:
    # - docker
    # - docker-compose
    - common
    - postgres

- become: yes
  hosts: bastion
  name: deploy-linkin
  roles:
    - common
    - docker
    - nginx
    - linkin