version: "3"

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  linkin:
    build: .
    # ports:
    #   - "3000:3000"
    environment:
      DATABASE_URL: "postgres://linkin:linkin123@db:5432/linkin"
      HASHSALT: "123" # random secret key
      NODE_ENV: "production"
    depends_on:
      - db
      - migrate
    labels:
      - "traefik.http.routers.linkin.rule=Host(`[ec2ip]`)"

  migrate:
    build: .
    command: >
      sh -c "npm run prismamigrateprod
      && npm run seed"
    environment:
      DATABASE_URL: "postgres://linkin:linkin123@db:5432/linkin"
      HASHSALT: "123" # random secret key
      NODE_ENV: "production"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_DB: "linkin"
      POSTGRES_USER: "linkin"
      POSTGRES_PASSWORD: "linkin123"
    volumes:
      #      - ./scripts/db-migrate.sql:/docker-entrypoint-initdb.d/db-migrate.sql
      - linkin-data:/var/lib/postgresql/data
volumes:
  linkin-data:
