- become: yes
  hosts: all
  name: docker-install
  tasks:
    - name: Add the user 'ansibleuser' and add it to 'sudo'
      user:
        name: ansibleuser
        group: sudo

    - name: Update all packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600

    - name: Install a list of packages for docker
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Apply Nginx template
      template:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

    # - name: Enable new site
    #   shell:
    #     cmd: "cat /etc/nginx/sites-available/default"
    #   args:
    #     executable: /bin/bash

    # - name: Enable new site
    #   shell:
    #     cmd: "systemctl status nginx"
    #   args:
    #     executable: /bin/bash

    - name: docker gpg setup
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        update_cache: yes
        state: present

    - name: Update repositories cache
      apt:
        update_cache: yes

    - name: Install docker-ce
      apt:
        name: docker-ce

    - name: add ubuntu to docker
      user:
        name: ubuntu
        group: docker

    - name: add ansibleuser to docker
      user:
        name: ansibleuser
        group: docker

    - name: get platform
      shell: "uname -s"
      args:
        executable: /bin/bash
      register: platform

    - name: get architecture
      shell: "uname -m"
      args:
        executable: /bin/bash
      register: arch

    - name: install docker-compose
      # remote_user: ubuntu
      get_url:
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-{{platform.stdout}}-{{arch.stdout}}
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"

    # - name: systemctl status nginx
    #   shell:
    #     cmd: "systemctl status nginx"
    #   args:
    #     executable: /bin/bash

  
  handlers:
    - name: Restart Nginx
      shell:
        cmd: "systemctl restart nginx"
      args:
        executable: /bin/bash
      # service:
      #   name: nginx
      #   state: restarted 
      #   systemctl restart nginx       

      

