# - name: Clone linkin
#   git:
#     repo: https://github.com/RizkyRajitha/linkin.git
#     dest: /home/linkin


- name: Copy docker-compose.yml
  copy:
    src: ../../../docker-compose.yml
    dest: /home/ubuntu



- name: docker compose up
  docker_compose:
    # cmd: "docker-compose up -d"
    project_src: /home/ubuntu
  register: output

- debug: msg="{{ output }}"

- meta: end_play
