- name: Copy docker-compose.yml
  copy:
    src: templates/docker-compose.yml
    dest: /home/ubuntu

- name: docker compose up
  docker_compose:
    project_src: /home/ubuntu
  register: output

- debug: msg="{{ output }}"

- meta: end_play
