- name: docker gpg setup
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    update_cache: yes
    state: present

- name: Update repositories cache
  apt:
    update_cache: yes


- name: Install docker-ce
  apt:
    name: docker-ce

- name: add ubuntu to docker
  user:
    name: ubuntu
    group: docker

- name: add ansibleuser to docker
  user:
    name: ansibleuser
    group: docker