- name: Install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Apply Nginx template
  template:
    src: files/nginx.conf
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx handle

- name: Enable new site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Restart Nginx handle

- name: Restart Nginx no handle
  systemd:
    state: restarted
    name: nginx
    daemon_reload: yes

- name: Ensure mongodb is started
  service:
    name: nginx
    state: started
  register: nginx_service_started

- debug: msg="{{ nginx_service_started }}"
